<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product</name>
   <tag></tag>
   <elementGuidId>9bdba7ae-d7e9-4694-b3a4-10db14d5b619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/div/div/nav/a[2]/ul/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73e483b3-31bc-449b-b928-cab3de95aa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters css-1klraep-MuiButtonBase-root-MuiListItemButton-root</value>
      <webElementGuid>d093936b-0532-4198-a541-7f29680385e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c1e7130-b97a-4110-9ac3-c3dc1e22c25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4139500a-5a2d-45fe-aed0-fe0ad1517312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product</value>
      <webElementGuid>1ffcfc2a-929d-4ae3-ab54-66525d39dbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page MuiBox-root css-k008qs&quot;]/nav[@class=&quot;MuiBox-root css-1mn6oro&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked css-12de4fs-MuiDrawer-docked&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft css-12i7wg6-MuiPaper-root-MuiDrawer-paper&quot;]/div[@class=&quot;sidebar-menu&quot;]/nav[@class=&quot;MuiList-root MuiList-padding MuiList-dense sidebar css-h4y409-MuiList-root&quot;]/a[@class=&quot;MuiListItem-root MuiListItem-dense MuiListItem-gutters MuiListItem-padding css-n6de37-MuiListItem-root&quot;]/ul[@class=&quot;MuiList-root MuiList-padding css-drdxl8-MuiList-root&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters css-1klraep-MuiButtonBase-root-MuiListItemButton-root&quot;]</value>
      <webElementGuid>b58f4a5f-f1c2-4e74-9a91-3000ad9efc9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/div/div/nav/a[2]/ul/div</value>
      <webElementGuid>f259b6e8-532f-4195-858b-fcb6b2116208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login success'])[1]/preceding::div[26]</value>
      <webElementGuid>44a6343e-e17f-4fac-8746-9aa9a01a7f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Produk'])[1]/preceding::div[31]</value>
      <webElementGuid>145910a4-208b-4508-ace3-9bdcda136fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/ul/div</value>
      <webElementGuid>d8873b8e-717d-4c8b-b197-c4fcb26eb539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Product' or . = 'Product')]</value>
      <webElementGuid>1385825a-c60b-4aa2-922b-7093bef16e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
