<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Maksimal Peserta_max_quota</name>
   <tag></tag>
   <elementGuidId>92cf2d18-791f-4c71-86f0-93d1d16a465f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max_quota</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max_quota']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95023212-ac6c-4a10-86dc-34d473db7767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>562a09ea-da13-48d5-9725-18a659edbe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max_quota</value>
      <webElementGuid>a7f78f4b-e55b-4312-aa15-ebde3a740ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max_quota</value>
      <webElementGuid>8d3af3ce-d158-46cd-99ed-2549e0aac553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>95501958-a133-49f8-a169-97add6401ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>aff455a1-1a32-4618-9138-341bfbabf11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max_quota&quot;)</value>
      <webElementGuid>76fcefed-735c-40a0-a6fb-33daf7bebe7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max_quota']</value>
      <webElementGuid>e57e7116-5c93-467f-8c40-e0f254aea2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div[2]/div/div[2]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>08ad533b-4d8e-4952-89ab-40b53b16fab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>51295e1f-3474-454c-a7e5-3fa1cd5582e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'max_quota' and @name = 'max_quota' and @type = 'number']</value>
      <webElementGuid>bfa60366-7cf7-41cb-92d1-dac90ee91f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
