<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link ZoomGmeet_url</name>
   <tag></tag>
   <elementGuidId>33931ae1-46d8-4a53-83b6-e723e77fa9ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fea56ef0-d18d-4ec3-8ea8-e46bcc9022ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9ae0ee4-bc91-440a-b26b-39ce8a16cc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>0ed0170f-01b8-4541-845b-cbc7643e3858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>aee80ced-6ae2-413b-a8be-7d0cc5bc6b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>70e418dc-26b1-4c23-a72c-e699d20837d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>0de33f46-2632-4fc0-b7aa-8b367a95efb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;url&quot;)</value>
      <webElementGuid>8026e203-3b2e-4c46-8d3a-1363da4e0045</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='url']</value>
      <webElementGuid>88f795d9-f1d3-4f83-a5cf-154cb0c6f17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div[3]/div/div/div[3]/div/input</value>
      <webElementGuid>f99ec4b1-a85e-4b73-9ab0-c144114c074c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f1984c3f-7442-4549-858f-af4bad8fb7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'url' and @name = 'url' and @type = 'url']</value>
      <webElementGuid>eabcde48-47b1-420f-8b6a-62101aae6336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
