<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ini syaratn</name>
   <tag></tag>
   <elementGuidId>4e987a69-68ee-405c-a2fd-08b234d5d325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms_and_conditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='terms_and_conditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e78f8450-37bd-4ba1-846a-bf92ea6a1fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f2a44a1c-8c76-443f-9753-cd62a4b4af8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1174b58e-7d37-4849-a847-52df849eabaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>2c9958b5-f253-4a29-9cb9-23386f076036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>d5bae887-7e95-4c7a-9e13-13a373fc563b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-1sqnrkk-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>4183f309-655c-43de-ba9c-4f20813516a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ini syaratn</value>
      <webElementGuid>342f34a8-1141-47f2-bbc3-e4f651311286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms_and_conditions&quot;)</value>
      <webElementGuid>b8bed191-487a-4146-bc25-49e130554fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='terms_and_conditions']</value>
      <webElementGuid>53d3b1fd-fa4c-419f-bd2f-4ccdfaab3352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>df6a7e3b-52f3-4892-9098-d64eb079a5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/following::textarea[1]</value>
      <webElementGuid>9a5f2e91-8b35-4080-a090-ca4293ffaf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ini syaratn']/parent::*</value>
      <webElementGuid>7250bd69-3dd1-49ad-b042-78ec6fd12452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>e8dbf8a5-383a-4a22-80fe-b948769ec821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'terms_and_conditions' and @name = 'terms_and_conditions' and (text() = 'ini syaratn' or . = 'ini syaratn')]</value>
      <webElementGuid>30ff745b-6a00-48ef-a990-27e60321540a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
