<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ini sy</name>
   <tag></tag>
   <elementGuidId>77f4e8c5-013e-46f9-99cc-25ce61a5ab58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms_and_conditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='terms_and_conditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>28c872bf-52ba-4a48-8c4b-3ffe314ed8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6ca651a5-5102-4652-a440-eb0d3c844b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c39b8df-ccbd-4205-8941-51829c732542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>5e7caa31-7e8f-46fa-89ef-b775f2907836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>e57bdacb-6766-4308-8050-1475ea3b1ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-1sqnrkk-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>0766cb44-1f20-4ea0-a899-80a0de3fc04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ini sy</value>
      <webElementGuid>bdb05429-ae08-4912-9d7a-30c6f9ee3255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms_and_conditions&quot;)</value>
      <webElementGuid>6873998a-4da2-40bb-bb99-23f5dbad2fe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='terms_and_conditions']</value>
      <webElementGuid>90907fb3-92ef-4dc6-8a2f-07401b19b314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>435a5660-85db-409d-bafe-5cf4b1883392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/following::textarea[1]</value>
      <webElementGuid>6714af04-e34f-4b13-b0d9-2424fed4d1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ini sy']/parent::*</value>
      <webElementGuid>bcc327fb-0b21-4964-ae72-c3b8cc165f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>a5a53033-88b2-4112-801a-e80abad59985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'terms_and_conditions' and @name = 'terms_and_conditions' and (text() = 'ini sy' or . = 'ini sy')]</value>
      <webElementGuid>3ba31c5a-ee92-4996-89e7-d04a61ac4781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
