<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ini_1 (1)</name>
   <tag></tag>
   <elementGuidId>d7c13c23-8daa-4b62-a839-dc531c53f037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms_and_conditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='terms_and_conditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fe0b87e0-39ef-4e52-b7fd-b8cd955a520d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>39ce33c5-444f-4983-ac5c-7bcf5b19e617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f0d49d2-a0b5-4476-ba11-7e6057b5f57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>2dcbc299-5c0f-470e-8fba-3b06ce71b805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>d80a2439-03eb-424e-828a-15e094ad63ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-1sqnrkk-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>f1b3953d-644f-48e5-b2d0-15a78c853cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ini </value>
      <webElementGuid>784c90d2-48d0-42a8-a45f-aa6b79670e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms_and_conditions&quot;)</value>
      <webElementGuid>bb16ea08-b1ef-4915-9dc4-7488632e0577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='terms_and_conditions']</value>
      <webElementGuid>491f47a2-7fa9-47ab-8731-cffdaef1bad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>6ab49bf3-8d77-4a90-9d22-748caf2b95c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/following::textarea[1]</value>
      <webElementGuid>e0ae309d-3056-4f18-a595-76b2f07b0b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ini']/parent::*</value>
      <webElementGuid>bdc512c0-d7b9-4295-aabe-5fc8a4a8d03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>e2a0c82c-8279-489e-9b92-b369e3c12e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'terms_and_conditions' and @name = 'terms_and_conditions' and (text() = 'ini ' or . = 'ini ')]</value>
      <webElementGuid>12ba9f16-b006-4019-be08-7642aa220eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
