<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ini (1)</name>
   <tag></tag>
   <elementGuidId>1b87e7f7-87aa-4ff5-a7fc-906f638fbdc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms_and_conditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='terms_and_conditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d91532bf-b1c0-442e-938d-9cd9493d33e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ea5fb9c1-22d6-4534-91df-b064c763afcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>878c21f7-08c6-45fa-8c00-869be984eab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>adcb9dba-8f15-4757-a02f-18ec6de29b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>4a7dcc07-e5f3-4905-84ca-2fe6ee5fdab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-1sqnrkk-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>d96ec4e4-bff1-4d19-87fc-1cfa67627cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ini</value>
      <webElementGuid>f29516bc-4788-4bd8-958b-1373643cac77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms_and_conditions&quot;)</value>
      <webElementGuid>b97b0467-75a6-4dd6-89e9-32b16be373d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='terms_and_conditions']</value>
      <webElementGuid>66f486be-42f7-4ac3-ad7d-34102632fd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>a6ab0287-ea1c-4bfb-9775-1ce76f6754e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/following::textarea[1]</value>
      <webElementGuid>c0fc0d3b-06e9-4a97-9eda-5ced955ddc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ini']/parent::*</value>
      <webElementGuid>c4a3859a-76a2-4a0a-a8ec-ecdcef3390c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/textarea</value>
      <webElementGuid>f74f1329-3992-47ad-b2e0-d84a9a35e24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'terms_and_conditions' and @name = 'terms_and_conditions' and (text() = 'ini' or . = 'ini')]</value>
      <webElementGuid>6c74f7bf-fd1a-4de4-bde5-3593cfca9aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
