<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Blog</name>
   <tag></tag>
   <elementGuidId>610e2156-09c2-45ce-aa77-47ecd94b1891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/div/div/nav/a[3]/ul/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2be05732-41ba-40d8-bb73-df02b24b4996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body2 MuiListItemText-primary css-1s7q9pl-MuiTypography-root</value>
      <webElementGuid>efc16404-e16c-4850-a0bd-4bd71aa40bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>9f1c1950-2b80-481c-9452-ea376be8d4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page MuiBox-root css-k008qs&quot;]/nav[@class=&quot;MuiBox-root css-1mn6oro&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked css-12de4fs-MuiDrawer-docked&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft css-12i7wg6-MuiPaper-root-MuiDrawer-paper&quot;]/div[@class=&quot;sidebar-menu&quot;]/nav[@class=&quot;MuiList-root MuiList-padding MuiList-dense sidebar css-h4y409-MuiList-root&quot;]/a[@class=&quot;MuiListItem-root MuiListItem-dense MuiListItem-gutters MuiListItem-padding css-n6de37-MuiListItem-root&quot;]/ul[@class=&quot;MuiList-root MuiList-padding css-drdxl8-MuiList-root&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-dense MuiListItemButton-gutters css-1klraep-MuiButtonBase-root-MuiListItemButton-root&quot;]/div[@class=&quot;MuiListItemText-root MuiListItemText-dense css-tlelie-MuiListItemText-root&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body2 MuiListItemText-primary css-1s7q9pl-MuiTypography-root&quot;]</value>
      <webElementGuid>5ed7fcfd-fd2e-4b27-81b0-ec7bb16c9361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/div/div/nav/a[3]/ul/div/div[2]/p</value>
      <webElementGuid>b394975c-c81b-4887-9656-054861da01d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Produk'])[1]/preceding::p[8]</value>
      <webElementGuid>d6b5c5e5-94a7-4831-8c9b-4cac667eb811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Order'])[1]/preceding::p[8]</value>
      <webElementGuid>9fa2dbb1-d814-420b-a2a1-18bd6b634e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>26b87c73-55e8-4025-a87e-bd1b5cad0905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/ul/div/div[2]/p</value>
      <webElementGuid>24edcb3e-98f2-4a05-b319-fa8ad7ef198a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>5a013744-b5df-48f6-b903-6235b37bc4d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
